"""Gemini QnA response schema."""

from typing import Literal
from pydantic import BaseModel, Field


class GeminiQnAResponse(BaseModel):
    """Pydantic schema matching the structured JSON format generated by Gemini."""

    answer_text: str = Field(
        description="The short, concise response to the user's question, usually 1 to 3 sentences."
    )
    answer_kind: Literal["video_grounded", "self_observation_boundary", "general_guidance", "safety_boundary", "fallback"] = Field(
        description="The categorization of the generated answer."
    )
    grounding_sources: list[str] = Field(
        default_factory=list,
        description="List of sources from the context used to answer (e.g. 'trainer_instruction', 'exercise_description', 'transcript')."
    )
    spoken_safe: bool = Field(
        default=True,
        description="Flag indicating if this answer is suitable and safe to be spoken aloud via TTS."
    )
